apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  labels:
    app.kubernetes.io/instance: watchtower
  name: watchtower-secrets
  namespace: cicd
spec:
  itemPath: vaults/kube/items/watchtower-secrets
